language: php

matrix:
    include:
        - php: 7.2
          env: SYMFONY_REQUIRE=^3
        - php: 7.3
          env: SYMFONY_REQUIRE=^3
        - php: 7.4
          env: SYMFONY_REQUIRE=^3
        - php: 7.2
          env: SYMFONY_REQUIRE=^4
        - php: 7.3
          env: SYMFONY_REQUIRE=^4
        - php: 7.4
          env: SYMFONY_REQUIRE=^4
        - php: 7.2
          env: SYMFONY_REQUIRE=^5
        - php: 7.3
          env: SYMFONY_REQUIRE=^5
        - php: 7.4
          env: SYMFONY_REQUIRE=^5

install:
    - composer require symfony/flex --no-update
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
